<?php

use Illuminate\Database\Seeder;

use Vanguard\Models\TvStation;

/**
 * This will loop through and create a tv station and associate with a publisher
 * (If that tv station and publisher is not created yet)
 */
class TvStationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $station_list = $this->getTVStationList();
        foreach ($station_list as $station) {
            $station_attrs = array(
                'name' => $station['station'],
                'type' => $station['station_type'],
                'state' => $station['state'],
                'city' => $station['city'],
                'region' => $station['region'],
                'key' => md5("{$station['station']}-{$station['station_type']}-{$station['state']}-{$station['city']}-{$station['region']}")
            );
            TvStation::firstOrCreate($station_attrs);
        }
    }

    protected function getTVStationList()
    {
        $station_list = array (
            0 =>
            array (
                'id' => 1,
                'station' => 'Activate',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            1 =>
            array (
                'id' => 2,
            'station' => 'Africa Magic (Hausa)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            2 =>
            array (
                'id' => 3,
            'station' => 'Africa Magic (Yoruba)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            3 =>
            array (
                'id' => 4,
                'station' => 'Africa Magic Epic',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            4 =>
            array (
                'id' => 5,
                'station' => 'Africa Magic Family',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            5 =>
            array (
                'id' => 6,
                'station' => 'Africa Magic Igbo',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            6 =>
            array (
                'id' => 7,
                'station' => 'Africa Magic Showcase',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            7 =>
            array (
                'id' => 8,
                'station' => 'Africa Magic Urban',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            8 =>
            array (
                'id' => 9,
                'station' => 'AIT International',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            9 =>
            array (
                'id' => 10,
                'station' => 'Alpha TV Channel 113 Nnobi',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            10 =>
            array (
                'id' => 11,
                'station' => 'AMC',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            11 =>
            array (
                'id' => 12,
                'station' => 'AMC Movies',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            12 =>
            array (
                'id' => 13,
                'station' => 'AMC Music',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            13 =>
            array (
                'id' => 14,
                'station' => 'AMC Series',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            14 =>
            array (
                'id' => 15,
                'station' => 'Arewa 24',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            15 =>
            array (
                'id' => 16,
                'station' => 'BBC Lifestyle',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            16 =>
            array (
                'id' => 17,
                'station' => 'BBC News',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            17 =>
            array (
                'id' => 18,
                'station' => 'BET',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            18 =>
            array (
                'id' => 19,
                'station' => 'Bollywood',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            19 =>
            array (
                'id' => 20,
                'station' => 'Cartoon Network',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            20 =>
            array (
                'id' => 21,
                'station' => 'CCTV 4',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            21 =>
            array (
                'id' => 22,
                'station' => 'Channels TV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            22 =>
            array (
                'id' => 23,
                'station' => 'CNN',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            23 =>
            array (
                'id' => 24,
                'station' => 'Comedy Central',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            24 =>
            array (
                'id' => 25,
                'station' => 'Discovery Channel',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            25 =>
            array (
                'id' => 26,
                'station' => 'Discovery Family',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            26 =>
            array (
                'id' => 27,
                'station' => 'Discovery Idx',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            27 =>
            array (
                'id' => 28,
                'station' => 'Discovery Science',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            28 =>
            array (
                'id' => 29,
                'station' => 'E! Entertainment',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            29 =>
            array (
                'id' => 30,
                'station' => 'Fox Crime',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            30 =>
            array (
                'id' => 31,
                'station' => 'Fox Entertainment',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            31 =>
            array (
                'id' => 32,
            'station' => 'Fox Int (GOtv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            32 =>
            array (
                'id' => 33,
                'station' => 'Fox Movie',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            33 =>
            array (
                'id' => 34,
                'station' => 'Fox News',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            34 =>
            array (
                'id' => 35,
                'station' => 'Fox Sports',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            35 =>
            array (
                'id' => 36,
                'station' => 'Iroko 1',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            36 =>
            array (
                'id' => 37,
                'station' => 'Iroko 2',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            37 =>
            array (
                'id' => 38,
                'station' => 'Kwese Free Sports',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            38 =>
            array (
                'id' => 39,
                'station' => 'Kwese Free Sports Nigeria ch. 290',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            39 =>
            array (
                'id' => 40,
                'station' => 'Kwese Sports 1 ch. 301',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            40 =>
            array (
                'id' => 41,
                'station' => 'Kwese Sports 2 ch. 302',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            41 =>
            array (
                'id' => 42,
                'station' => 'M-Net Movies Action',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            42 =>
            array (
                'id' => 43,
                'station' => 'M-Net Movies City',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            43 =>
            array (
                'id' => 44,
                'station' => 'M-Net Movies Premiere',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            44 =>
            array (
                'id' => 45,
                'station' => 'M-Net Movies Star',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            45 =>
            array (
                'id' => 46,
                'station' => 'M-Net Movies Zone',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            46 =>
            array (
                'id' => 47,
                'station' => 'M-Net Smile',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            47 =>
            array (
                'id' => 48,
                'station' => 'M-Net West',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            48 =>
            array (
                'id' => 49,
                'station' => 'MBC 1',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            49 =>
            array (
                'id' => 50,
                'station' => 'MBC 3',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            50 =>
            array (
                'id' => 51,
                'station' => 'MBC 4',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            51 =>
            array (
                'id' => 52,
                'station' => 'MBC Action',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            52 =>
            array (
                'id' => 53,
                'station' => 'MBC Max',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            53 =>
            array (
                'id' => 54,
                'station' => 'MTV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            54 =>
            array (
                'id' => 55,
                'station' => 'MTV Base',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            55 =>
            array (
                'id' => 56,
                'station' => 'My TV Africa',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            56 =>
            array (
                'id' => 57,
                'station' => 'My TV Series',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            57 =>
            array (
                'id' => 58,
                'station' => 'My TV Yoruba',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            58 =>
            array (
                'id' => 59,
                'station' => 'National Geographic',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            59 =>
            array (
                'id' => 60,
                'station' => 'National Geographic Wild',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            60 =>
            array (
                'id' => 61,
                'station' => 'Nick Jr',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            61 =>
            array (
                'id' => 62,
                'station' => 'Nick Toons',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            62 =>
            array (
                'id' => 64,
                'station' => 'NTA Entertainment',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            63 =>
            array (
                'id' => 65,
                'station' => 'NTA Hausa',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            64 =>
            array (
                'id' => 66,
                'station' => 'NTA Igbo',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            65 =>
            array (
                'id' => 67,
                'station' => 'NTA Knowledge',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            66 =>
            array (
                'id' => 68,
                'station' => 'NTA Lagos',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            67 =>
            array (
                'id' => 69,
                'station' => 'NTA News 24',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            68 =>
            array (
                'id' => 70,
                'station' => 'NTA Parliamentary',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            69 =>
            array (
                'id' => 71,
                'station' => 'NTA Sports',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            70 =>
            array (
                'id' => 72,
                'station' => 'NTA Yoruba',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            71 =>
            array (
                'id' => 73,
                'station' => 'PIUS TV Africa',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            72 =>
            array (
                'id' => 74,
            'station' => 'RFI (France) Hausa Service',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            73 =>
            array (
                'id' => 75,
            'station' => 'RFI (France) World Service',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            74 =>
            array (
                'id' => 76,
                'station' => 'ROK 2',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            75 =>
            array (
                'id' => 77,
                'station' => 'ROK 3',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            76 =>
            array (
                'id' => 78,
            'station' => 'SS Select 4 Africa (GOtv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            77 =>
            array (
                'id' => 79,
            'station' => 'Silverbird (STV)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            78 =>
            array (
                'id' => 80,
            'station' => 'Silverbird International (STV)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            79 =>
            array (
                'id' => 81,
                'station' => 'Sky News',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            80 =>
            array (
                'id' => 82,
                'station' => 'Sound City',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            81 =>
            array (
                'id' => 83,
            'station' => 'SS 1 Africa (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            82 =>
            array (
                'id' => 84,
            'station' => 'SS 10 Nigeria (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            83 =>
            array (
                'id' => 85,
            'station' => 'SS 11 Nigeria (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            84 =>
            array (
                'id' => 86,
            'station' => 'SS 12 Nigeria (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            85 =>
            array (
                'id' => 87,
            'station' => 'SS 2 Africa (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            86 =>
            array (
                'id' => 88,
            'station' => 'SS 3 Nigeria (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            87 =>
            array (
                'id' => 89,
            'station' => 'SS 4 Africa (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            88 =>
            array (
                'id' => 90,
            'station' => 'SS 5 Nigeria (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            89 =>
            array (
                'id' => 91,
            'station' => 'SS 6 Africa (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            90 =>
            array (
                'id' => 92,
            'station' => 'SS 7 Nigeria (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            91 =>
            array (
                'id' => 93,
            'station' => 'SS 8 Nigeria (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            92 =>
            array (
                'id' => 94,
            'station' => 'SS 9 Africa (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            93 =>
            array (
                'id' => 95,
            'station' => 'SS Blitz (DStv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            94 =>
            array (
                'id' => 97,
                'station' => 'Star life',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            95 =>
            array (
                'id' => 98,
                'station' => 'Star World',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            96 =>
            array (
                'id' => 99,
                'station' => 'Startimes Bollywood',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            97 =>
            array (
                'id' => 100,
                'station' => 'Startimes Bollywood Africa',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            98 =>
            array (
                'id' => 101,
                'station' => 'Startimes Orisun',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            99 =>
            array (
                'id' => 102,
                'station' => 'Startimes Yoruba',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            100 =>
            array (
                'id' => 103,
                'station' => 'Studio Universal',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            101 =>
            array (
                'id' => 104,
            'station' => 'SuperSport 2 (GOtv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            102 =>
            array (
                'id' => 105,
            'station' => 'SuperSport 3 (GOtv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            103 =>
            array (
                'id' => 106,
            'station' => 'SuperSport Blitz (GOtv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            104 =>
            array (
                'id' => 107,
            'station' => 'SuperSport Select 1 (GOtv)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            105 =>
            array (
                'id' => 108,
                'station' => 'Telemundo',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            106 =>
            array (
                'id' => 109,
                'station' => 'Trace Naija',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            107 =>
            array (
                'id' => 110,
            'station' => 'V.O.A. (Voice Of America)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            108 =>
            array (
                'id' => 111,
            'station' => 'V.O.N. (Voice Of Nigeria), Lagos',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            109 =>
            array (
                'id' => 112,
                'station' => 'Vuzu Amp',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            110 =>
            array (
                'id' => 113,
                'station' => 'WAP TV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            111 =>
            array (
                'id' => 114,
                'station' => 'Wazobia TV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            112 =>
            array (
                'id' => 115,
                'station' => 'Zee World',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            113 =>
            array (
                'id' => 118,
                'station' => 'ABS TV',
                'station_type' => 'regional',
                'state' => 'Anambra',
                'city' => '',
                'region' => 'south east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            114 =>
            array (
                'id' => 119,
                'station' => 'Africa Magic',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            115 =>
            array (
                'id' => 120,
                'station' => 'AIT',
                'station_type' => 'network',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            116 =>
            array (
                'id' => 121,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Abuja',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            117 =>
            array (
                'id' => 122,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Bauchi',
                'city' => '',
                'region' => 'north east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            118 =>
            array (
                'id' => 123,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Borno',
                'city' => '',
                'region' => 'north east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            119 =>
            array (
                'id' => 124,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Edo',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            120 =>
            array (
                'id' => 125,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Enugu',
                'city' => '',
                'region' => 'south east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            121 =>
            array (
                'id' => 126,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Ilorin',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            122 =>
            array (
                'id' => 127,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Kaduna',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            123 =>
            array (
                'id' => 128,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Kano',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            124 =>
            array (
                'id' => 129,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            125 =>
            array (
                'id' => 130,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Oyo',
                'city' => '',
                'region' => 'south west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            126 =>
            array (
                'id' => 131,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Plateau',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            127 =>
            array (
                'id' => 132,
            'station' => 'AIT (Natl)',
                'station_type' => 'network',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            128 =>
            array (
                'id' => 133,
                'station' => 'AIT',
                'station_type' => 'regional',
                'state' => 'Rivers',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            129 =>
            array (
                'id' => 134,
                'station' => 'AMC',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            130 =>
            array (
                'id' => 135,
                'station' => 'BATV',
                'station_type' => 'regional',
                'state' => 'Bauchi',
                'city' => '',
                'region' => 'north east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            131 =>
            array (
                'id' => 136,
                'station' => 'BBC',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            132 =>
            array (
                'id' => 137,
                'station' => 'BCA TV',
                'station_type' => 'regional',
                'state' => 'Abia',
                'city' => '',
                'region' => 'sout east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            133 =>
            array (
                'id' => 138,
                'station' => 'BCOS CH 28',
                'station_type' => 'regional',
                'state' => 'Oyo',
                'city' => '',
                'region' => 'south west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            134 =>
            array (
                'id' => 139,
                'station' => 'BRTV',
                'station_type' => 'regional',
                'state' => 'Borno',
                'city' => '',
                'region' => 'north east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            135 =>
            array (
                'id' => 140,
                'station' => 'Canal TV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            136 =>
            array (
                'id' => 141,
                'station' => 'Capital TV',
                'station_type' => 'regional',
                'state' => 'Kaduna',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            137 =>
            array (
                'id' => 142,
                'station' => 'CBS',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            138 =>
            array (
                'id' => 143,
                'station' => 'CCTV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            139 =>
            array (
                'id' => 144,
                'station' => 'Channels TV',
                'station_type' => 'network',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            140 =>
            array (
                'id' => 145,
                'station' => 'Channels TV',
                'station_type' => 'regional',
                'state' => 'Abuja',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            141 =>
            array (
                'id' => 146,
                'station' => 'Channels TV',
                'station_type' => 'regional',
                'state' => 'Edo',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            142 =>
            array (
                'id' => 147,
                'station' => 'Channels TV',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            143 =>
            array (
                'id' => 148,
                'station' => 'CRTV',
                'station_type' => 'regional',
                'state' => 'CrossRiver',
                'city' => 'Ikom',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            144 =>
            array (
                'id' => 149,
                'station' => 'CRTV',
                'station_type' => 'regional',
                'state' => 'CrossRiver',
                'city' => 'Calabar',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            145 =>
            array (
                'id' => 150,
                'station' => 'CTV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            146 =>
            array (
                'id' => 151,
                'station' => 'CTV Channel 67',
                'station_type' => 'regional',
                'state' => 'Kano',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            147 =>
            array (
                'id' => 152,
                'station' => 'Discovery',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            148 =>
            array (
                'id' => 153,
                'station' => 'Disney',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            149 =>
            array (
                'id' => 154,
                'station' => 'DITV',
                'station_type' => 'regional',
                'state' => 'Kaduna',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            150 =>
            array (
                'id' => 155,
                'station' => 'EBS CH 55',
                'station_type' => 'regional',
                'state' => 'Edo',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            151 =>
            array (
                'id' => 156,
                'station' => 'Ekiti',
                'station_type' => 'regional',
                'state' => 'Ekiti',
                'city' => '',
                'region' => 'south west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            152 =>
            array (
                'id' => 157,
                'station' => 'ETV',
                'station_type' => 'regional',
                'state' => 'Enugu',
                'city' => '',
                'region' => 'south east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            153 =>
            array (
                'id' => 158,
                'station' => 'Fox',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            154 =>
            array (
                'id' => 160,
                'station' => 'Galaxy TV',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            155 =>
            array (
                'id' => 161,
                'station' => 'Galaxy TV',
                'station_type' => 'regional',
                'state' => 'Oyo',
                'city' => '',
                'region' => 'south west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            156 =>
            array (
                'id' => 162,
                'station' => 'Iroko',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            157 =>
            array (
                'id' => 164,
                'station' => 'ITV',
                'station_type' => 'regional',
                'state' => 'Abuja',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            158 =>
            array (
                'id' => 165,
                'station' => 'ITV',
                'station_type' => 'regional',
                'state' => 'Edo',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            159 =>
            array (
                'id' => 167,
                'station' => 'KSTV',
                'station_type' => 'regional',
                'state' => 'Kaduna',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            160 =>
            array (
                'id' => 168,
                'station' => 'KTV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            161 =>
            array (
                'id' => 169,
                'station' => 'KTV',
                'station_type' => 'regional',
                'state' => 'Ilorin',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            162 =>
            array (
                'id' => 171,
            'station' => 'Kwese Free Sports (KFS) UHF 32',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            163 =>
            array (
                'id' => 172,
                'station' => 'Kwese Int',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            164 =>
            array (
                'id' => 174,
                'station' => 'Liberty TV',
                'station_type' => 'regional',
                'state' => 'Kaduna',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            165 =>
            array (
                'id' => 176,
                'station' => 'LTV',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            166 =>
            array (
                'id' => 177,
                'station' => 'M-Net',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            167 =>
            array (
                'id' => 178,
                'station' => 'MBC',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            168 =>
            array (
                'id' => 180,
                'station' => 'MITV',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            169 =>
            array (
                'id' => 181,
                'station' => 'MITV',
                'station_type' => 'regional',
                'state' => 'Oyo',
                'city' => '',
                'region' => 'south west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            170 =>
            array (
                'id' => 182,
                'station' => 'MST',
                'station_type' => 'regional',
                'state' => 'Anambra',
                'city' => '',
                'region' => 'south east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            171 =>
            array (
                'id' => 184,
                'station' => 'My TV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            172 =>
            array (
                'id' => 185,
                'station' => 'Nat Geographic',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            173 =>
            array (
                'id' => 186,
                'station' => 'Nickelodeon',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            174 =>
            array (
                'id' => 187,
            'station' => 'NSTV (NTA Station)',
                'station_type' => 'regional',
                'state' => 'Niger',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            175 =>
            array (
                'id' => 188,
                'station' => 'NTA',
                'station_type' => 'network',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            176 =>
            array (
                'id' => 189,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Abia',
                'city' => '',
                'region' => 'south east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            177 =>
            array (
                'id' => 190,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Abuja',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            178 =>
            array (
                'id' => 191,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Anambra',
                'city' => '',
                'region' => 'south east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            179 =>
            array (
                'id' => 192,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Bauchi',
                'city' => '',
                'region' => 'north east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            180 =>
            array (
                'id' => 193,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Borno',
                'city' => '',
                'region' => 'north east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            181 =>
            array (
                'id' => 194,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'CrossRiver',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            182 =>
            array (
                'id' => 195,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Edo',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            183 =>
            array (
                'id' => 196,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Ekiti',
                'city' => '',
                'region' => 'south west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            184 =>
            array (
                'id' => 197,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Enugu',
                'city' => '',
                'region' => 'south east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            185 =>
            array (
                'id' => 198,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Ilorin',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            186 =>
            array (
                'id' => 199,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Kaduna',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            187 =>
            array (
                'id' => 200,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Kano',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            188 =>
            array (
                'id' => 201,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Niger',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            189 =>
            array (
                'id' => 202,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Oyo',
                'city' => '',
                'region' => 'south west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            190 =>
            array (
                'id' => 203,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Plateau',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            191 =>
            array (
                'id' => 204,
                'station' => 'NTA',
                'station_type' => 'regional',
                'state' => 'Sokoto',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            192 =>
            array (
                'id' => 205,
                'station' => 'NTA 2 CH',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            193 =>
            array (
                'id' => 206,
                'station' => 'NTA CH',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            194 =>
            array (
                'id' => 207,
                'station' => 'NTA CH 45 & 7',
                'station_type' => 'regional',
                'state' => 'Oyo',
                'city' => '',
                'region' => 'south west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            195 =>
            array (
                'id' => 208,
                'station' => 'NTA Channel 35',
                'station_type' => 'regional',
                'state' => 'Anambra',
                'city' => '',
                'region' => 'south east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            196 =>
            array (
                'id' => 209,
                'station' => 'NTA International',
                'station_type' => 'regional',
                'state' => 'Abuja',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            197 =>
            array (
                'id' => 210,
                'station' => 'NTA Port',
                'station_type' => 'regional',
                'state' => 'Rivers',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            198 =>
            array (
                'id' => 211,
                'station' => 'On TV',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            199 =>
            array (
                'id' => 212,
                'station' => 'OSBC',
                'station_type' => 'regional',
                'state' => 'Osun',
                'city' => '',
                'region' => 'south west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            200 =>
            array (
                'id' => 214,
                'station' => 'PRTV',
                'station_type' => 'regional',
                'state' => 'Plateau',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            201 =>
            array (
                'id' => 215,
                'station' => 'ROK',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            202 =>
            array (
                'id' => 216,
                'station' => 'RSTV Port',
                'station_type' => 'regional',
                'state' => 'Rivers',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            203 =>
            array (
                'id' => 217,
                'station' => 'Silverbird',
                'station_type' => 'network',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            204 =>
            array (
                'id' => 218,
                'station' => 'Silverbird',
                'station_type' => 'regional',
                'state' => 'Abuja',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            205 =>
            array (
                'id' => 220,
                'station' => 'Silverbird Television',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            206 =>
            array (
                'id' => 221,
                'station' => 'Silverbird TV',
                'station_type' => 'regional',
                'state' => 'Edo',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            207 =>
            array (
                'id' => 222,
                'station' => 'Silverbird TV',
                'station_type' => 'regional',
                'state' => 'Plateau',
                'city' => '',
                'region' => 'north east',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            208 =>
            array (
                'id' => 223,
                'station' => 'Silverbird TV CH 31',
                'station_type' => 'regional',
                'state' => 'Rivers',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            209 =>
            array (
                'id' => 224,
                'station' => 'Sokoto State',
                'station_type' => 'regional',
                'state' => 'Sokoto',
                'city' => '',
                'region' => 'north west',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            210 =>
            array (
                'id' => 225,
            'station' => 'SS (DSTV)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            211 =>
            array (
                'id' => 226,
            'station' => 'SS (GOTV)',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            212 =>
            array (
                'id' => 227,
                'station' => 'Star TV',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            213 =>
            array (
                'id' => 228,
                'station' => 'Startimes',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            214 =>
            array (
                'id' => 229,
                'station' => 'SuperScreen',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            215 =>
            array (
                'id' => 230,
                'station' => 'Trace',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            216 =>
            array (
                'id' => 232,
                'station' => 'TVC',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            217 =>
            array (
                'id' => 233,
                'station' => 'Viasat',
                'station_type' => 'satellite',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            218 =>
            array (
                'id' => 235,
                'station' => 'Wazobia Max',
                'station_type' => 'regional',
                'state' => 'Abuja',
                'city' => '',
                'region' => 'north central',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            219 =>
            array (
                'id' => 236,
                'station' => 'Wazobia Max',
                'station_type' => 'regional',
                'state' => 'Lagos',
                'city' => '',
                'region' => 'lagos',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            220 =>
            array (
                'id' => 237,
                'station' => 'Wazobia Max',
                'station_type' => 'regional',
                'state' => 'Rivers',
                'city' => '',
                'region' => 'south south',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            221 =>
            array (
                'id' => 238,
                'station' => 'Wazobia Max',
                'station_type' => 'regional',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-11 01:05:25',
                'updated_at' => '2019-04-11 01:05:25',
            ),
            222 =>
            array (
                'id' => 239,
                'station' => 'CRTV',
                'station_type' => 'regional',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-15 20:04:53',
                'updated_at' => '2019-04-15 20:04:53',
            ),
            223 =>
            array (
                'id' => 240,
                'station' => 'Galaxy TV',
                'station_type' => 'regional',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-15 20:04:53',
                'updated_at' => '2019-04-15 20:04:53',
            ),
            224 =>
            array (
                'id' => 241,
                'station' => 'ITV',
                'station_type' => 'regional',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-15 20:04:53',
                'updated_at' => '2019-04-15 20:04:53',
            ),
            225 =>
            array (
                'id' => 242,
                'station' => 'KSTV',
                'station_type' => 'regional',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-15 20:04:53',
                'updated_at' => '2019-04-15 20:04:53',
            ),
            226 =>
            array (
                'id' => 243,
                'station' => 'Kwese',
                'station_type' => 'network',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-15 20:04:53',
                'updated_at' => '2019-04-15 20:04:53',
            ),
            227 =>
            array (
                'id' => 244,
                'station' => 'Liberty TV',
                'station_type' => 'regional',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-15 20:04:53',
                'updated_at' => '2019-04-15 20:04:53',
            ),
            228 =>
            array (
                'id' => 245,
                'station' => 'LTV',
                'station_type' => 'regional',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-15 20:04:53',
                'updated_at' => '2019-04-15 20:04:53',
            ),
            229 =>
            array (
                'id' => 246,
                'station' => 'MITV',
                'station_type' => 'regional',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-15 20:04:53',
                'updated_at' => '2019-04-15 20:04:53',
            ),
            230 =>
            array (
                'id' => 247,
                'station' => 'PRTV',
                'station_type' => 'regional',
                'state' => '',
                'city' => '',
                'region' => '',
                'created_at' => '2019-04-15 20:04:53',
                'updated_at' => '2019-04-15 20:04:53',
            ),
        );
        return $station_list;
    }

    protected function getRegionalTvStations()
    {
        return [
            ['name' => 'BCA TV','type' => 'Regional', 'state' => 'Abia', 'city' => 'Umuahia', 'region' => 'South East'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Abia', 'city' => 'Aba', 'region' => 'South East'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Abia', 'city' => 'Umuahia', 'region' => 'South East'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Abuja', 'city' => 'Abuja', 'region' => 'North Central'],
            ['name' => 'Channels TV', 'type' => 'Regional', 'state' => 'Abuja', 'city' => 'Abuja', 'region' => 'North Central'],
            ['name' => 'ITV', 'type' => 'Regional', 'state' => 'Abuja', 'city' => 'Abuja', 'region' => 'North Central'],
            ['name' => 'Silverbird TV', 'type' => 'Regional', 'state' => 'Abuja', 'city' => 'Abuja', 'region' => 'North Central'],
            ['name' => 'Wazobia Max', 'type' => 'Regional', 'state' => 'Abuja', 'city' => 'Abuja', 'region' => 'North Central'],

            ['name' => 'ABS', 'type' => 'Regional', 'state' => 'Anambra', 'city' => 'Onitsha', 'region' => 'South East'],
            ['name' => 'ABS', 'type' => 'Regional', 'state' => 'Anambra', 'city' => 'Awka', 'region' => 'South East'],
            ['name' => 'MST', 'type' => 'Regional', 'state' => 'Anambra', 'city' => 'Obosi', 'region' => 'South East'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Anambra', 'city' => 'Awka', 'region' => 'South East'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Anambra', 'city' => 'Onitsha', 'region' => 'South East'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Bauchi', 'city' => 'Bauchi', 'region' => 'North East'],
            ['name' => 'BATV', 'type' => 'Regional', 'state' => 'Bauchi', 'city' => 'Bauchi', 'region' => 'North East'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Bauchi', 'city' => 'Bauchi', 'region' => 'North East'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Borno', 'city' => 'Borno', 'region' => 'North East'],
            ['name' => 'BRTV', 'type' => 'Regional', 'state' => 'Borno', 'city' => 'Maiduguri', 'region' => 'North East'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Borno', 'city' => 'Maiduguri', 'region' => 'North East'],

            ['name' => 'CRTV', 'type' => 'Regional', 'state' => 'Cross River', 'city' => 'Calabar', 'region' => 'South South'],
            ['name' => 'CRTV', 'type' => 'Regional', 'state' => 'Cross River', 'city' => 'Ikom', 'region' => 'South South'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Cross River', 'city' => 'Calabar', 'region' => 'South South'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Edo', 'city' => 'Benin', 'region' => 'South South'],
            ['name' => 'Channels TV', 'type' => 'Regional', 'state' => 'Edo', 'city' => '', 'region' => 'South South'],
            ['name' => 'EBS', 'type' => 'Regional', 'state' => 'Edo', 'city' => 'Benin', 'region' => 'South South'],
            ['name' => 'ITV', 'type' => 'Regional', 'state' => 'Edo', 'city' => 'Benin', 'region' => 'South South'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Edo', 'city' => 'Benin', 'region' => 'South South'],
            ['name' => 'Silverbird TV', 'type' => 'Regional', 'state' => 'Edo', 'city' => 'Benin', 'region' => 'South South'],

            ['name' => 'Ekiti State Televison', 'type' => 'Regional', 'state' => 'Ekiti', 'city' => '', 'region' => 'South West'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Ekiti', 'city' => 'Ado-Ekiti', 'region' => 'South West'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Enugu', 'city' => 'Enugu', 'region' => 'South East'],
            ['name' => 'ETV', 'type' => 'Regional', 'state' => 'Enugu', 'city' => 'Enugu', 'region' => 'South East'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Enugu', 'city' => 'Enugu', 'region' => 'South East'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Kaduna', 'city' => 'Kaduna', 'region' => 'North West'],
            ['name' => 'Capital TV', 'type' => 'Regional', 'state' => 'Kaduna', 'city' => 'Kaduna', 'region' => 'North West'],
            ['name' => 'DITV', 'type' => 'Regional', 'state' => 'Kaduna', 'city' => 'Kaduna', 'region' => 'North West'],
            ['name' => 'KSTV', 'type' => 'Regional', 'state' => 'Kaduna', 'city' => 'Kaduna', 'region' => 'North West'],
            ['name' => 'Liberty TV', 'type' => 'Regional', 'state' => 'Kaduna', 'city' => 'Kaduna', 'region' => 'North West'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Kaduna', 'city' => 'Kaduna', 'region' => 'North West'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Kaduna', 'city' => 'Kafanchan', 'region' => 'North West'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Kaduna', 'city' => 'Zaria', 'region' => 'North West'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Kaduna', 'city' => 'Birnin-Gwari', 'region' => 'North West'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Kano', 'city' => 'Kano', 'region' => 'North West'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Kano', 'city' => 'Kano', 'region' => 'North West'],
            ['name' => 'CTV', 'type' => 'Regional', 'state' => 'Kano', 'city' => 'Kano', 'region' => 'North West'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Kwara', 'city' => 'Ilorin', 'region' => 'North Central'],
            ['name' => 'KTV', 'type' => 'Regional', 'state' => 'Kwara', 'city' => 'Ilorin', 'region' => 'North Central'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Kwara', 'city' => 'Ilorin', 'region' => 'North Central'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'Channels TV', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'Galaxy TV', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'Kwese Free Sports', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'Lagos Continental', 'type' => 'Regional', 'state' => 'Lagos', 'city' => '', 'region' => 'Lagos'],
            ['name' => 'LTV', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'MITV', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'NTA 2', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'ONTV', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'Silverbird TV', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],
            ['name' => 'Super Screen', 'type' => 'Regional', 'state' => 'Lagos', 'city' => '', 'region' => 'Lagos'],
            ['name' => 'Wazobia Max', 'type' => 'Regional', 'state' => 'Lagos', 'city' => 'Lagos', 'region' => 'Lagos'],

            ['name' => 'NSTV', 'type' => 'Regional', 'state' => 'Niger', 'city' => 'Minna', 'region' => 'North Central'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Niger', 'city' => 'Minna', 'region' => 'North Central'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Oyo', 'city' => 'Ibadan', 'region' => 'South West'],
            ['name' => 'BCOS', 'type' => 'Regional', 'state' => 'Oyo', 'city' => 'Ibadan', 'region' => 'South West'],
            ['name' => 'Galaxy TV', 'type' => 'Regional', 'state' => 'Oyo', 'city' => 'Ibadan', 'region' => 'South West'],
            ['name' => 'MITV', 'type' => 'Regional', 'state' => 'Oyo', 'city' => 'Ibadan', 'region' => 'South West'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Oyo', 'city' => 'Ibadan', 'region' => 'South West'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Plateau', 'city' => 'Jos', 'region' => 'North Central'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Plateau', 'city' => 'Jos', 'region' => 'North Central'],
            ['name' => 'PRTV', 'type' => 'Regional', 'state' => 'Plateau', 'city' => 'Jos', 'region' => 'North Central'],
            ['name' => 'Silverbird TV', 'type' => 'Regional', 'state' => 'Plateau', 'city' => 'Jos', 'region' => 'North Central'],

            ['name' => 'AIT', 'type' => 'Regional', 'state' => 'Rivers', 'city' => 'Port Harcourt', 'region' => 'South South'],
            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Rivers', 'city' => 'Port Harcourt', 'region' => 'South South'],
            ['name' => 'RSTV', 'type' => 'Regional', 'state' => 'Rivers', 'city' => 'Port Harcourt', 'region' => 'South South'],
            ['name' => 'Silverbird TV', 'type' => 'Regional', 'state' => 'Rivers', 'city' => 'Port Harcourt', 'region' => 'South South'],
            ['name' => 'Wazobia Max', 'type' => 'Regional', 'state' => 'Rivers', 'city' => 'Port Harcourt', 'region' => 'South South'],

            ['name' => 'NTA', 'type' => 'Regional', 'state' => 'Sokoto', 'city' => 'Sokoto', 'region' => 'North West'],
            ['name' => 'Sokoto State Television', 'type' => 'Regional', 'state' => 'Sokoto', 'city' => '', 'region' => 'North West']
        ];
    }

    protected function getNationalTvStations()
    {
        return [
            ['name' => 'ABS TV','type' => 'Network', 'state' => '', 'city' => '', 'region' => ''],
            ['name' => 'CRTV','type' => 'Network', 'state' => '', 'city' => '', 'region' => ''],
            ['name' => 'OSBC','type' => 'Network', 'state' => '', 'city' => '', 'region' => ''],
            ['name' => 'KTV','type' => 'Network', 'state' => '', 'city' => '', 'region' => ''],
            ['name' => 'CTV','type' => 'Network', 'state' => '', 'city' => '', 'region' => ''],
            ['name' => 'KSTV','type' => 'Network', 'state' => '', 'city' => '', 'region' => ''],
            ['name' => 'Silverbird TV','type' => 'Network', 'state' => '', 'city' => '', 'region' => ''],
            ['name' => 'AIT','type' => 'Network', 'state' => '', 'city' => '', 'region' => ''],
        ];
    }
}


// php artisan db:seed --class=TvStationTableSeeder