version: '3'
services:

  #PHP Service
  publisher:
    networks:
    - faya_bridge
    external_links:
    - docker_mysql

  #Nginx Service
  webserver_publisher:
    ports:
    - "8070:80"

#Docker Networks
networks:
  faya_bridge:
    external:
      name: faya_bridge

#Volumes
volumes:
  dbdata:
    driver: local
