version: "2"
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    image: faya-app
    labels:
      - "traefik.backend=alpine"
      - "traefik.frontend.rule=Host:alpine.docker.localhost"
    ports:
      - "9000:80"
    environment:
      - MYSQL_HOST=database
      - APACHE_SERVER_NAME=alpine.docker.localhost
      - CONTAINER_TIMEZONE=UTC
      - PHP_SHORT_OPEN_TAG=On
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_HTML_ERRORS=On
      - PHP_DATE_TIMEZONE=UTC
      - PHP_XDEBUG_ENABLED=true
      - DB_HOST=database
      - DB_USERNAME=faya
      - DB_PASSWORD=faya
      - MEDIA_BUCKET=faya-dev-us-east-1-media
    volumes:
      - $HOME/.aws:$HOME/.aws
      # - ./:/app
    cap_add:
      - SYS_TIME
      - SYS_NICE

  database:
    image: mysql:5.7
    ports:
        - "33061:3306"
    environment:
      - MYSQL_DATABASE=faya
      - MYSQL_USER=faya
      - MYSQL_PASSWORD=faya
      - MYSQL_ROOT_PASSWORD=faya
      - TZ=UTC
    volumes:
      - $PWD/dev/mysql:/var/lib/mysql
      - $PWD/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
