version: "2"
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    image: faya-app
    labels:
      - "traefik.backend=alpine"
      - "traefik.frontend.rule=Host:alpine.docker.localhost"
    ports:
      - "9000:80"
    environment:
      - HOME=/home
      - AWS_REGION=us-east-1
      - MYSQL_HOST=database
      - APACHE_SERVER_NAME=alpine.docker.localhost
      - CONTAINER_TIMEZONE=UTC
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_DISPLAY_STARTUP_ERRORS=On
      - PHP_DATE_TIMEZONE=UTC
      - PHP_XDEBUG_ENABLED=true
      - DB_HOST=database
      - DB_USERNAME=faya
      - DB_PASSWORD=faya
      - MEDIA_BUCKET=faya-dev-us-east-1-media
      - PHP_MEMORY_LIMIT=256M
    volumes:
      - $HOME/.aws:/home/.aws:delegated
      - ./:/app:delegated
    cap_add:
      - SYS_TIME
      - SYS_NICE

  database:
    image: mysql:5.7
    ports:
        - "33061:3306"
    environment:
      - MYSQL_DATABASE=faya
      - MYSQL_USER=faya
      - MYSQL_PASSWORD=faya
      - MYSQL_ROOT_PASSWORD=faya
      - TZ=UTC
    volumes:
      - $PWD/dev/mysql:/var/lib/mysql:cached
      - $PWD/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # command: --lower_case_table_names=0

# docker compose issues with mounting on mac
# https://docs.docker.com/docker-for-mac/osxfs-caching/
