<?php

namespace Vanguard\Services\RateCard;

use Vanguard\Models\Ratecard\Ratecard;

class StoreSpecificRateCard extends StoreBaseRateCard
{
    protected $start_date;
    protected $end_date;
    protected $ratecard_type_id;

    public function __construct($company_id, $duration, $price, $start_time, $end_time, $rate_card_type, $title, $start_date, $end_date, $ratecard_type_id)
    {
        parent::__construct($company_id, $duration, $price, $start_time, $end_time, $rate_card_type, $title);
        $this->start_date = $start_date;
        $this->end_date = $end_date;
        $this->ratecard_type_id = $ratecard_type_id;
    }

    public function storeBaseRateCard()
    {
        $rate_card = parent::storeBaseRateCard(); // TODO: Change the autogenerated stub
        //updating the ratecard
        $get_ratecard = Ratecard::find($rate_card->id);
        $get_ratecard->start_date = $this->start_date ? $this->start_date : '';
        $get_ratecard->end_date = $this->end_date ? $this->end_date : '';
        $get_ratecard->ratecard_type_id = $this->ratecard_type_id ? $this->ratecard_type_id : '';
        $get_ratecard->save();
        return $get_ratecard;
    }

}
